### ISSUE TITLE
Edge 16 anchor jump links no longer work

### ISSUE THREAD

**Issue by Nooshu** [alphagov/gds-way#101]
I've just tested the GDS Way in Edge 16 (latest, released in October) and have noticed a strange issue where clicking on an anchor jump link in the left hand nav now has no effect.

The browser looks like it is trying to jump down, the URL hash changes for a second, then reverts back to its previous state.

![url-jump-link](https://user-images.githubusercontent.com/1223960/33015986-b3de509a-cde4-11e7-8b46-bd8e6a8a1d22.png)

**Note:** this has been tested in BrowserStack. It would be good to test and debug on a device actually running 16 rather than through the emulator. Would be worth investigating if a page refresh is being triggered, as that is what it looks to be doing.

Also Edge 15 and 14 work as expected, looks to be a 16 only issue.

**Comment by pgchamberlin** [comment]
That's a really weird one, because unless I'm much mistaken it's just a `<a href="#fragment">link</a>`. Spooky!
Do you have access to an Edge 16 device @Nooshu ?

**Comment by Nooshu** [comment]
I'm afraid not @pgchamberlin. I will ask about.

I have copied this issue [across to the tech docs repo](https://github.com/alphagov/tech-docs-template/issues/122) and will continue the conversation there.

**Comment by pgchamberlin** [comment]
👍
