### ISSUE TITLE
Determine the best way to back up GitHub repositories

### ISSUE THREAD

**Issue by techforevil** [alphagov/gds-way#11]
add guidance to https://github.com/alphagov/gds-tech/blob/gh-pages/source-code.md

questions from TechOps Forum 29.04.2017: 
* Can our deployment systems deploy from GitLab?
* How do we do account management on GitLab?
* What’s the commercial model for moving away from github enterprise, and for gitlab
* Do we need the ability to take a full archive or can we rely on the integrity of the git artefact?

**Comment by techforevil** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/9945756-174045597_3-s1-v1.png?transparent=1&palette=1&width=246)

**Comment by techforevil** [comment]
started https://docs.google.com/document/d/1su31cqg_TyvG3VoydsKyYwCz3WwwqTXTm5aCTNkjeBA/edit

**Comment by stephenharker** [comment]
Transferred to GDS Way Trello
