### ISSUE TITLE
Removing or rewording of the important note around node usage

### ISSUE THREAD

**Issue by Nooshu** [alphagov/gds-way#111]
I would like to have a conversation around the ["Important Note"](https://github.com/alphagov/gds-way/blob/master/source/manuals/programming-languages/nodejs/index.html.md.erb#L7) that can be seen on the "Using Node.js at GDS" page.

We currently don't have a Deputy Director Technology Operations at GDS to consult around this issue, and if we did would this person be the correct person to consult with and make this decision? Should this paragraph be reworded so that a decision is made from a key group of individuals using the new GDS Way Forum strategy that has recently been proposed? Or should the paragraph now be removed completely?

Node is already being used internally, and it is a language area that has a huge supporter base that has [matured greatly](https://nodejs.org/en/about/working-groups/) in the past few years. I'm concerned that this paragraph will immediately halt any consideration for using Node in projects, even when it could be the perfect technology to use.

**Comment by rboulton** [comment]
I think the appropriate group to make a decision on this will be the proposed (today) "Programme technical leads" group.  I'm working today and tomorrow on getting the initial set up and membership of that group defined, at which point we should discuss changing the GDS Way definition accordingly.

I'm personally keen that we review our strategy around Node.js soon.

**Comment by danmitchell-** [comment]
Some more context -
https://gds-way.cloudapps.digital/standards/programming-languages.html#languages-in-use-in-specific-contexts

“No new projects should use Node.js without prior consultation ”
“Node.js can be used to render a web interface for your service but should not be used to implement any significant ‘application logic’”
“Node.js is now frequently used in the wider software development ecosystem for building web application frontends.”

😖

**Comment by danielroseman** [comment]
Moved to Trello, closing.
