### ISSUE TITLE
Basic container guidance

### ISSUE THREAD

**Issue by willp-bl** [alphagov/gds-way#186]
It would be good to re-use all/some of the guidance Laura wrote in this PR - https://github.com/alphagov/gds-way/pull/89

If it can capture the way things are working right now it can be amended/expanded later as needed.

**Comment by soupdragon99** [comment]
There's a card in the GDS Way backlog for something on this. I do have the original guidance Laura put together, I'll raise a PR to open a discussion and people can update it as they see fit.

**Comment by soupdragon99** [comment]
raised [PR23](https://github.com/alphagov/gds-way/pull/213) to open discussion.
