### ISSUE TITLE
DNS test case tool writeup

### ISSUE THREAD

**Issue by techforevil** [alphagov/gds-way#22]
what did we learn? what else do we need to do?

**Comment by techforevil** [comment]
started https://docs.google.com/a/digital.cabinet-office.gov.uk/document/d/11BXe-mr_zd_GjVZhGQsCEw0_P14cSHhsFEpYqKbk50Q/edit?usp=drive_web

**Comment by danielroseman** [comment]
Everyone who was involved in that project has left and the draft is not helpful as it is, there doesn't seem to be much point in leaving this open.
