### ISSUE TITLE
Re: 'Linting Python at GDS'

### ISSUE THREAD

**Issue by denizgenc** [alphagov/gds-way#240]
Problem with 'Linting Python at GDS' (https://gds-way.cloudapps.digital/manuals/programming-languages/python/linting.html)

- I can't click on links that are on the last line before a new section

To reproduce:
- Find a link that is on a line just before a section - for example "Flake8 error codes list", or "by performing a PyPI search".
- Try to click on it. It won't work.
    - Neither will the link be highlighted when you hover over it.

I wonder if this issue is common to all GDS Way pages.

**Comment by SteveEvansGDS** [comment]
Looks like an issue across tech docs pages that have upgraded to 1.7.0: https://github.com/alphagov/tech-docs-template/issues/179

**Comment by deanwilson** [comment]
The links you mentioned now seem to be clickable so it looks like a fix has been implemented. Thank you for raising the issue and please re-open if it's still not working for you.
