### ISSUE TITLE
Include User support/Support operations on Technical Operations page

### ISSUE THREAD

**Issue by louzoid-gds** [alphagov/gds-way#401]
Since PR #400 we've added a Technical Operations page for the Cyber and RE pages to sit underneath: https://gds-way.cloudapps.digital/standards/technical-operations.html
We should also include content on User Support in this section as they are part of the Technical Operations programme.

A 'How GDS provides user support' page already exists here: https://gds-way.cloudapps.digital/standards/user-support.html

We should review this page and either move the content under the TO page or cross-link

**Comment by stephenharker** [comment]
User Support is now part of the Technology Pillar in CDIO so this issue is defunct now I think.

**Comment by stephenharker** [comment]
I think we should remove the https://gds-way.cloudapps.digital/standards/technical-operations.html page from GDS Way altogether and, if possible, redirect that URL to the CDIO page.

Similarly, the CDIO page in GDS Way ought to link to detailed content in the CO Intranet and CDIO Wikis once they exist.

**Comment by timblair** [comment]
> if possible, redirect that URL to the CDIO page

Redirects can be set up in [`config/tech-docs.yml`](https://github.com/alphagov/gds-way/blob/9f00d055/config/tech-docs.yml#L37-L42).
