### ISSUE TITLE
Re: 'HTML coding style' typo @ line 131

### ISSUE THREAD

**Issue by PaolaDMadd** [alphagov/gds-way#584]
Problem with 'HTML coding style' (https://gds-way.cloudapps.digital/manuals/programming-languages/html.html)

Hello I just noticed a typo on this page, here below the details:

@ line 131
"Links should not open new tabs or windows by default, but if users choose to **`to`** so (through keyboard[...]"
correct word is  **`do`**

regards 
Paola

**Comment by timblair** [comment]
Thanks for pointing this out, @PaolaDMadd!
