### ISSUE TITLE
Documentation of APIs

### ISSUE THREAD

**Issue by edent** [alphagov/gds-way#61]
(As suggested by Will Pearson.)

I know there's lots of discussion about APIs within GDS, but there's nothing currently in The GDS Way.  Should we add something around APIs?

The Open Standards team is currently evaluating whether we should mandate the use of OpenAPI v3 to document all our APIs.

See the discussion on https://github.com/alphagov/open-standards/issues/31

**Comment by MatMoore** [comment]
👍 This would be really helpful if it advises how to bring older APIs up to a better standard.

It would be great to have some guidance around versioning and deprecation, along the lines of  https://gdstechnology.blog.gov.uk/2016/07/26/considering-our-approach-to-api-iteration/

**Comment by danielroseman** [comment]
Moved discussion to existing Trello card, number 30
