### ISSUE TITLE
NodeJS guidance on Koa

### ISSUE THREAD

**Issue by tombye** [alphagov/gds-way#618]
The guidance on NodeJS currently recommends using the Express framework for web applications.

It has been suggested that [the Koa framework is now a better fit for how we advise writing NodeJS JavaScript](https://github.com/alphagov/gds-way/pull/606#issuecomment-838492982). While this is true, Koa's design encourages a different way of writing application code<sup>1</sup> which:
- requires developers to provide common features like routing, sessions, etc...
- has fewer conventions around how to write applications

GDS also currently has no examples of applications written in Koa in production.

While all of this is true, it also appears the guidance to use Express has prevented developers choosing Koa in the past, despite it potentially being a better fit.

This aims to collect the discussion in one place and gather evidence for how we advise developers choosing between Express and Koa and whether migrating to Koa from Express is something teams should consider.

<p>1. see <a href="https://github.com/alphagov/gds-way/pull/606#issuecomment-858537185">#606 (comment)</a> for more detail</p>

**Comment by timblair** [comment]
@tombye Have any further discussions on this happened? What can we do to move this forward?

**Comment by tombye** [comment]
@timblair doesn't look like it, I'd guess because no one has had to make a new NodeJS app at GDS since the last discussion happened so opinions around it are still kind of subjective.

I think the next review for the NodeJS pages is a good place to ask all those involved what their positions are on it then so I'm going to close this issue. If anyone feels strongly that GDS needs a more defined position on this in the meantime is welcome to re-open this issue or raise a new one.
