### ISSUE TITLE
Re: 'The GDS Way'

### ISSUE THREAD

**Issue by Aidan23Smith** [alphagov/gds-way#700]
Problem with 'The GDS Way' (https://gds-way.cloudapps.digital/)

Hi,

Just had a look through the GDS Way and and realised that the [How to store source code](https://gds-way.cloudapps.digital/standards/source-code.html) link doesn't appear to work.

I hope this helps,
Aidan

**Comment by philandstuff** [comment]
Ah I think this was unintentionally caused in #696 by @chao-xian

**Comment by mrwilson** [comment]
Thanks for letting us know @Aidan23Smith 

There's prior art for link checking and other linting (using `html-proofer`) in other projects using the tech docs template (such as [the GOV.UK Sign-In technical documentation](https://github.com/alphagov/di-authentication-tech-docs/blob/main/config.rb#L12))

Maybe that's worth folding into the GDS Way repo too.
