### ISSUE TITLE
Expand guidance on use of GitHub organisations to explain the GOV.UK One Login now uses govuk-one-login

### ISSUE THREAD

**Issue by pauldougan** [alphagov/gds-way#878]
Comment on 'Use GitHub' (https://gds-way.digital.cabinet-office.gov.uk/standards/source-code/use-github.html)

alphagov is no longer the only GitHub organisation for storing GDS code. The GOV.UK One Login team is moving into a separate organisation [govuk-one-login](https://github.com/govuk-one-login) so the guidance should acknowledge this

**Comment by louzoid-gds** [comment]
Updated as part of #884 so closing this issue
