### ISSUE TITLE
Last list anchors broken on mobile / tablet viewport

### ISSUE THREAD

**Issue by Nooshu** [alphagov/gds-way#99]
To reproduce:
- Goto: https://gds-way.cloudapps.digital/#standards
- Shrink the viewport down to approx 760px
- Try clicking on "storing source code" link
- Link not clickable due to following headings negative margin causing an overlap.

![margin-issue](https://user-images.githubusercontent.com/1223960/33012104-d653bcf8-cdd7-11e7-9e8b-f1baf78f580f.png)

Issue caused [here](https://github.com/alphagov/gds-way/blob/bb6a00f98d1bae9f708fe0e99589be818c3171c8/source/stylesheets/modules/_technical-documentation.scss#L54)
````
h3, h4, h5, h6 {
    @include heading-offset($gutter);
  }
````

Proposed fix:

1. Either remove usage of the mixin in this case and add specific styling manually (less padding, no negative margin)
2. Continue to use the mixin but add an override after it's usage

Option 1 seems like the cleanest to me with minimal impact.

**Comment by philandstuff** [comment]
Thanks for the detailed error report! I've seen something similar before but it's good to see an analysis of the problem, its causes, and ways to fix it. We've added this to our backlog to take a look at it.

**Comment by Nooshu** [comment]
No problem @philandstuff. [PR for option 1](https://github.com/alphagov/gds-way/pull/100) here if the team are happy with the fix. If not just throw it away :)

**Comment by Nooshu** [comment]
Closing issue as it has been duplicated [here](https://github.com/alphagov/tech-docs-template/issues/123).
